### ISSUE TITLE
Close button

### ISSUE THREAD

**Issue by JonErickson** [dzenbot/DZNWebViewController#14]
Am I missing something, or how is one suppose to close the view controller once presented?

**Comment by sachinkesiraju** [comment]
I found a way to add a back button to the web controller. 
You'll need to add the bar button item to DZNWebViewController's navigation item rather than to the navigation item on the navigation controller.

```
DZNWebViewController *controller = [[DZNWebViewController alloc] initWithURL:[NSURL URLWithString:@"https://google.com/"]];
UINavigationController *navController = [[UINavigationController alloc] initWithRootViewController:controller];
UIBarButtonItem *closeButton = [[UIBarButtonItem alloc] initWithTitle:@"CLOSE" style:UIBarButtonItemStylePlain target:self action:@selector(closeButtonWithWebView:)];
controller.navigationItem.rightBarButtonItem = closeButton;
```

**Comment by abidullah** [comment]
@sachinkesiraju   i tried the same but when i select close button the view controller exits but crashes , any idea how u did it , can u share that code

**Comment by sachinkesiraju** [comment]
Hmm, it works just fine for me. Here's the code I'm using.
```
@property (strong, nonatomic) UINavigationController *navController; (in the @interface)

- (void) close
{
    NSLog(@"Closing view");
    [_navController dismissViewControllerAnimated:YES completion:nil];
}

- (void) openWebsiteWithURL: (NSString *) URL
{
    DZNWebViewController *webViewController = [[DZNWebViewController alloc] initWithURL:[NSURL URLWithString:URL]];
    _navController = [[UINavigationController alloc] initWithRootViewController:webViewController];
    webViewController.supportedWebActions = DZNWebActionAll;
    webViewController.supportedWebNavigationTools = DZNWebNavigationToolAll;
    webViewController.showLoadingProgress = YES;
    webViewController.navigationItem.rightBarButtonItem = [[UIBarButtonItem alloc] initWithTitle:@"Close" style:UIBarButtonItemStylePlain target:self action:@selector(close)];
    [self presentViewController:_navController animated:YES completion:nil];
}
```
And this is what it looks like 
![ios simulator screen shot jan 20 2015 8 52 43 pm](https://cloud.githubusercontent.com/assets/7436977/5819791/73c19c20-a0e6-11e4-8ea4-7ddf6cc793b6.png)

**Comment by haoyuexing** [comment]
@abidullah i have the same issue. when i close the VC. crash. did u fix it?

**Comment by abidullah** [comment]
@haoyuexing No it still crash

**Comment by DreamingInBinary** [comment]
You can fix this by using a static context on your wrapper class to open a URL. Here is mine:

    //
    //  WebHelper.h
    //  HaloTimer
    //
    //  Created by Jordan Morgan on 2/24/15.
    //  Copyright (c) 2015 Jordan Morgan. All rights reserved.
    //

    #import <Foundation/Foundation.h>
    @class DZNWebViewController;

    @interface WebHelper : NSObject
    + (void)openURL:(NSURL *)url fromViewController:(UIViewController *)sender;
    @end

And the implementation:

    //
    //  WebHelper.m
    //  HaloTimer
    //
    //  Created by Jordan Morgan on 2/24/15.
    //  Copyright (c) 2015 Jordan Morgan. All rights reserved.
    //

    #import "WebHelper.h"
    #import "DZNWebViewController.h"

    static UINavigationController *navVC = nil;
    static DZNWebViewController *webVC = nil;

    @implementation WebHelper

    + (void)openURL:(NSURL *)url fromViewController:(UIViewController *)sender
    {
        if (!navVC && !webVC)
        {
            webVC = [[DZNWebViewController alloc] initWithURL:url];
            navVC = [[UINavigationController alloc] initWithRootViewController:webVC];
        }
        else
        {
             webVC.URL = url;
        }
    
        webVC.supportedWebNavigationTools = DZNWebNavigationToolAll;
        webVC.supportedWebActions = DZNWebActionAll;
        webVC.showLoadingProgress = YES;
        webVC.allowHistory = YES;
        webVC.hideBarsWithGestures = YES;
        webVC.navigationItem.leftBarButtonItem = [[UIBarButtonItem alloc]     initWithBarButtonSystemItem:UIBarButtonSystemItemCancel target:self action:@selector(close)];
    
        [sender presentViewController:navVC animated:YES completion:NULL];
    }

    + (void)close
    {
        [navVC dismissViewControllerAnimated:YES completion:nil];
    }
    @end

**Comment by haoyuexing** [comment]
@DreamingInBinary It's worked. but another issue here. open first page -> close -> open second page. now "back button" can be click. It will back to the first page. i think the logic is wrong. how can i open this VC without the previous record?! thanks.
