### ISSUE TITLE
Can't install DZNWebViewController v3 via Pod

### ISSUE THREAD

**Issue by YaroslavVoloshyn** [dzenbot/DZNWebViewController#36]
I want install  DZNWebViewController v3 via Pod. For this I use - pod 'DZNWebViewController', '~> 3.1' and I get the result:

[!] Unable to satisfy the following requirements:
- `DZNWebViewController (= 3.1)` required by `Podfile`
Specs satisfying the `DZNWebViewController (= 3.1)` dependency were found, but they required a higher minimum deployment target.

If I use pod 'DZNWebViewController', than it installs v2.

**Comment by markymc** [comment]
@YaroslavVoloshyn I'm having the same issue. Would you be able to share how you handled this in the end?

**Comment by markymc** [comment]
@YaroslavVoloshyn  Ah please ignore my question above. It's because my app supports iOS 7 but v3.x of DZNWebViewController requires iOS 8. :)
